## Pandas

In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:

df = pd.DataFrame(np.arange(0, 20).reshape(5,4), index = ['Row1', 'Row2', 'Row3' , 'Row4', 'Row5'], columns = ['Column1', 'Column2', 'Column3', 'Column4'], )

In [3]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:

# Save to csv
df.to_csv('test1.csv')

In [5]:
## Accessing to the elements
# variant 1 is .loc   variant 2 is .iloc
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [6]:
# Check the type
type(df.loc['Row1'])

pandas.Series

In [7]:
df.iloc[:, :]

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
## Take the elements from the column2
df.iloc[:, 1:]

      Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [9]:
df.iloc[0:2,0:2]

      Column1  Column2
Row1        0        1
Row2        4        5

In [10]:
#check type
type(df.iloc[:,:])

pandas.DataFrame

In [11]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Column1, dtype: int64

In [12]:
type(df.iloc[0:2, 0])

pandas.Series

In [13]:
# Take the elements from the Column2
df.iloc[:,1:]

      Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [14]:

# convert df into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [15]:
df['Column1'].value_counts()

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [16]:

df.iloc[:,:].shape

(5, 4)

In [17]:
df.iloc[:,1:].shape

(5, 3)

In [18]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [19]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [20]:
df[['Column3', 'Column4']]

      Column3  Column4
Row1        2        3
Row2        6        7
Row3       10       11
Row4       14       15
Row5       18       19

In [21]:


df = pd.read_csv('mercedesbenz.csv')

In [22]:

df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [23]:
df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [25]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
df2 = pd.read_csv('test1.csv', sep=',')

In [27]:
df2.head()

  Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [28]:
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [29]:
df[df['y'] == 100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
1727,3452,100.0,y,aa,as,d,d,ae,j,c,...,0,1,0,0,0,0,0,0,0,0
2764,5525,100.0,t,b,m,a,d,p,h,f,...,0,0,1,0,0,0,0,0,0,0

In [30]:
from io import StringIO, BytesIO

In [31]:
data = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

In [32]:

type(data)

str

In [33]:
StringIO()

In [34]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [35]:
data2 = ('col1; col2; col3\n'
       'x;y;1\n'
       'a;b;2\n'
       'c;d;3')

In [36]:
pd.read_csv(StringIO(data2), sep=';')

  col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [37]:
#df3 = pd.read_csv(StringIO(data2), usecols=['col1','col2'], sep=';')

In [38]:
print(data)

col1,col2,col3
x,y,1
a,b,2
c,d,3

In [39]:
pd.read_csv(StringIO(data), usecols=['col1','col2'])

  col1 col2
0    x    y
1    a    b
2    c    d

In [40]:
data3 = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')

In [41]:
print(data3)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [42]:
df = pd.read_csv(StringIO(data3), dtype=object)

In [43]:
df

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [44]:
df['a'][1]

'5'

In [45]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [46]:
# We can show all types with another types
df = pd.read_csv(StringIO(data3), dtype={'b':int, 'c':float, 'a':'Int64'})

In [47]:
df

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [48]:
df.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [49]:
data = ('index,a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orange,cow,10')

In [50]:
# If we want doing index our index we must show with index_col
pd.read_csv(StringIO(data), index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [51]:
# without index_col shown like that
pd.read_csv(StringIO(data))

   index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [52]:
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')

In [53]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [54]:
pd.read_csv(StringIO(data), index_col = False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [55]:
pd.read_csv(StringIO(data), usecols = ['b','c'], index_col = False)

        b    c
0   apple  bat
1  orange  cow

In [56]:
import requests
from io import StringIO
import pandas as pd

url = 'https://download.bls.gov/pub/time.series/cu/cu.item'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                  '(KHTML, like Gecko) Chrome/153.0.0.0 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.9',
    'Referer': 'https://www.bls.gov/'
}

response = requests.get(url, headers=headers)

print(response.status_code)

403

In [57]:
## URL to csv - Etot sayt vydayot oshibku 403 - t.e. net dostupa k nemu
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [ ]:
## URL to csv
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

In [ ]:
df.head()

## Read Json files

In [58]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df1 = pd.read_json(StringIO(Data))

In [59]:
pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [60]:
df.head()

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

#### Convert JSON to CSV

In [61]:
df.to_csv('wine.csv')

In [62]:
df=pd.read_csv('wine.csv')

In [63]:
df.head()

   Unnamed: 0  a   b     c   d
0           0  1   2   3.0   4
1           1  5   6   7.0   8
2           2  9  10  11.0  12

In [64]:
# convert JSON to different json formats

df.to_json(orient='index')

'{"0":{"Unnamed: 0":0,"a":1,"b":2,"c":3.0,"d":4},"1":{"Unnamed: 0":1,"a":5,"b":6,"c":7.0,"d":8},"2":{"Unnamed: 0":2,"a":9,"b":10,"c":11.0,"d":12}}'

In [65]:
df1

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [66]:
df1.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [67]:
df1.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [68]:
df.to_json(orient="records")

'[{"Unnamed: 0":0,"a":1,"b":2,"c":3.0,"d":4},{"Unnamed: 0":1,"a":5,"b":6,"c":7.0,"d":8},{"Unnamed: 0":2,"a":9,"b":10,"c":11.0,"d":12}]'

## Reading HTML contents

In [69]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'

dfs = pd.read_html(url)

In [70]:
type(dfs)

list

In [71]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

In [72]:
import requests
import pandas as pd
from io import StringIO

url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'

headers = {
    'User-Agent': 'Mozilla/5.0'
}

response = requests.get(url_mcc, headers=headers)

print(response.status_code)

200

In [73]:
#url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
#dfs = pd.read_html(url_mcc, match='Country', header=0)

In [74]:
dfs = pd.read_html(
    StringIO(response.text),
    match='Country',
    header=0
)

print(len(dfs))

1

In [75]:
dfs[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

## Reading Excel Files

In [76]:
df_excel = pd.read_excel('Excel_Sample.xlsx')

In [77]:
df_excel.head()

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

## Pickling

In [79]:
df_excel.to_pickle('df_excel')

In [80]:
df_pickl = pd.read_pickle('df_excel')

In [82]:
df_pickl.head()

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15